- name: expense project
  hosts: localhost
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: clean default code in nginx
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: make a directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: unarchive frontend code
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copy frontend conf
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Enable and restart service
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: yes

