- name: expense project
  hosts: localhost
  become: yes
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: mysql secure installation
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

    - name: start mysql service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes